version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb+srv://dineshravikumar05:ddYpe4BiCg9vJcIu@cluster0.owj09c7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
